module.exports = {
	API_CACHE_TIME: process.env.NEXT_PUBLIC_API_CACHE_TIME, // minutes
	API_HOST_NAME: 'http://127.0.0.1:8080',

	SITE_URL: process.env.NEXT_PUBLIC_SITE_URL,
	AUTH_STATUS: {
		NOT_AUTHENTICATED: 'NOT_AUTHENTICATED',
		AUTHENTICATED: 'AUTHENTICATED',
	},
	ERROR_CODE: {
		UNAUTHORIZED: 401,
		TOKEN_IS_NOT_VALID: 1009,
	},
};
